namespace WowPacketParser.Enums
{
    public enum QuestInfo
    {
        None       = 0,
        Group      = 1,
        Class      = 21,
        PvP        = 41,
        Raid       = 62,
        Dungeon    = 81,
        WorldEvent = 82,
        Legendary  = 83,
        Escort     = 84,
        Heroic     = 85,
        Raid10     = 88,
        Raid25     = 89,
        Scenario   = 98,
        Account    = 102,
        SideQuest  = 104,
        Artifact = 107,
        WorldQuest = 109,
        EpicWorldQuest = 110,
        EliteWorldQuest = 111,
        EpicEliteWorldQuest = 112,
        PvPWorldQuest = 113,
        AidWorldQuest = 114,
        FightingPetsWorldQuest = 115,
        ForgeWorldQuest = 116,
        LeatherWorldQuest = 117,
        AlchemyWorldQuest = 118,
        HerbalWorldQuest = 119,
        MiningWorldQuest = 120,
        TailorWorldQuest = 121,
        EngineeringWorldQuest = 122,
        EnchantingWorldQuest = 123,
        SkinWorldQuest = 124,
        JewelleryWorldQuest = 125,
        InscriptionWorldQuest = 126,
        EmissaryQuest = 128,
        ArchaeologyWorldQuest = 129,
        FishWorldQuest = 130,
        CookWorldQuest = 131,
        RareWorldQuest = 135,
        RareEliteWorldQuest = 136,
        InstanceWorldQuest = 137,
        LegionInvasionWorldQuest1 = 139,
        RatingAward = 140,
        RaidWorldQuest = 141,
        LegionInvasionEliteWorldQuest = 142,
        AlliedForcesDonate = 143,
        AlliedForcesWorldQuest = 144,
        AlliedForcesInstanceWorldQuest = 145,
        LegionInvasionWorldQuest2 = 146,
        Search = 148,
    }
}
